apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spring
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring
    spec:
      containers:
      - image: spring-1 
        name: spring
        ports:
        - name: spring
          containerPort: 7070    
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring
  name: spring
spec:
  type: NodePort
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    name: spring
